// Auto-generated by main.js — do not edit by hand.
// Loaded by Node (require) AND by logs/Commandlogs.html (<script src="useslog.js">).
var commandLogs = [
  {
    "time": "2026-06-19T21:49:19.513Z",
    "type": "slash",
    "command": "about",
    "username": "lyrics_loop",
    "userId": "1328479692394725396",
    "guildName": "Discord mod test",
    "guildId": "1516151829778399243",
    "channelName": "general",
    "channelId": "1516151831108124684",
    "messageLink": "https://discord.com/channels/1516151829778399243/1516151831108124684/1517647493490282607"
  },
  {
    "time": "2026-06-19T21:52:47.395Z",
    "type": "slash",
    "command": "about",
    "username": "lyrics_loop",
    "userId": "1328479692394725396",
    "guildName": "Discord mod test",
    "guildId": "1516151829778399243",
    "channelName": "general",
    "channelId": "1516151831108124684",
    "messageLink": "https://discord.com/channels/1516151829778399243/1516151831108124684/1517648364928237630"
  },
  {
    "time": "2026-06-19T21:52:56.128Z",
    "type": "slash",
    "command": "warn",
    "username": "lyrics_loop",
    "userId": "1328479692394725396",
    "guildName": "Discord mod test",
    "guildId": "1516151829778399243",
    "channelName": "general",
    "channelId": "1516151831108124684",
    "messageLink": "https://discord.com/channels/1516151829778399243/1516151831108124684/1517648399585902703"
  },
  {
    "time": "2026-06-19T21:57:24.492Z",
    "type": "slash",
    "command": "updates",
    "username": "lyrics_loop",
    "userId": "1328479692394725396",
    "guildName": "Discord mod test",
    "guildId": "1516151829778399243",
    "channelName": "general",
    "channelId": "1516151831108124684",
    "messageLink": "https://discord.com/channels/1516151829778399243/1516151831108124684/1517649527367008392"
  },
  {
    "time": "2026-06-19T22:02:49.572Z",
    "type": "slash",
    "command": "about",
    "username": "lyrics_loop",
    "userId": "1328479692394725396",
    "guildName": "Discord mod test",
    "guildId": "1516151829778399243",
    "channelName": "general",
    "channelId": "1516151831108124684",
    "messageLink": "https://discord.com/channels/1516151829778399243/1516151831108124684/1517650891363188857"
  },
  {
    "time": "2026-06-19T22:04:25.031Z",
    "type": "slash",
    "command": "warn",
    "username": "lyrics_loop",
    "userId": "1328479692394725396",
    "guildName": "Discord mod test",
    "guildId": "1516151829778399243",
    "channelName": "general",
    "channelId": "1516151831108124684",
    "messageLink": "https://discord.com/channels/1516151829778399243/1516151831108124684/1517651289599639594"
  },
  {
    "time": "2026-06-19T22:06:06.128Z",
    "type": "prefix",
    "command": "warn",
    "username": "lyrics_loop",
    "userId": "1328479692394725396",
    "guildName": "Discord mod test",
    "guildId": "1516151829778399243",
    "channelName": "general",
    "channelId": "1516151831108124684",
    "messageLink": "https://discord.com/channels/1516151829778399243/1516151831108124684/1517651712842924062"
  }
];
if (typeof module !== 'undefined' && module.exports) {
    module.exports = commandLogs;
}
if (typeof window !== 'undefined') {
    window.commandLogs = commandLogs;
}
